version: '3'
# npm run db-up
# docker ps = para veer lso contenedores
# docker exec -it "NAMES" psql -U postgres = para que docker acceda al servicio dentro del contenedor (en este caso el servidor de la BD) y trabaje directamente con esa bd
# docker exec -it reg003-chat-app_postgres_1 psql -U postgres 
# Ahora puedo utilizar comandos para interactuar con postgres desde el terminal (lista de las bd): \l
# \c 'nombre de la bd' = para acceder a la bd
# \dt para ver la lista de los datos de la bd (tablas)
# 
services:
  postgres:
    image: 'postgres:13-alpine'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: default_database
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: 'dpage/pgadmin4:5.6'
    depends_on:
      - postgres
    ports:
      - 15432:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  postgres:
  pgadmin:
